from enum import StrEnum


class UserRole(StrEnum):
    OWNER = "OWNER"
    STAFF = "STAFF"
    ADMIN = "ADMIN"


class WhatsAppStatus(StrEnum):
    CONNECTED = "CONNECTED"
    DISCONNECTED = "DISCONNECTED"
    PENDING = "PENDING"


class TokenType(StrEnum):
    USER_TOKEN = "USER_TOKEN"
    SYSTEM_USER_TOKEN = "SYSTEM_USER_TOKEN"


class TokenSource(StrEnum):
    EMBEDDED_SIGNUP = "EMBEDDED_SIGNUP"
    MANUAL = "MANUAL"


class AutomationStatus(StrEnum):
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"


class AuditAction(StrEnum):
    USER_REGISTERED = "USER_REGISTERED"
    USER_LOGIN = "USER_LOGIN"
    USER_LOGOUT = "USER_LOGOUT"

    GYM_UPDATED = "GYM_UPDATED"

    WHATSAPP_CONNECTED = "WHATSAPP_CONNECTED"
    WHATSAPP_DISCONNECTED = "WHATSAPP_DISCONNECTED"

    AUTOMATION_ENABLED = "AUTOMATION_ENABLED"
    AUTOMATION_DISABLED = "AUTOMATION_DISABLED"
