from enum import StrEnum


class ErrorCode(StrEnum):
    """
    Centralized error codes for the entire application.
    These codes are returned in the error response payload to identify specific issues.
    """

    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"

    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"

    GYM_NOT_FOUND = "GYM_NOT_FOUND"

    WHATSAPP_NOT_CONNECTED = "WHATSAPP_NOT_CONNECTED"
    WHATSAPP_ALREADY_CONNECTED = "WHATSAPP_ALREADY_CONNECTED"

    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    INVALID_TOKEN = "INVALID_TOKEN"

    META_API_ERROR = "META_API_ERROR"
    META_INVALID_TOKEN = "META_INVALID_TOKEN"
    META_CONNECTION_FAILED = "META_CONNECTION_FAILED"

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

